### ISSUE TITLE
Need help for install

### ISSUE THREAD

**Issue by tkleinhakisa** [mozart-analytics/sqsd#1]
Hi, i am starting a project including beanstalk workers and i was looking at solution for development to have the interaction between workers and sqs.

I tried to install your project but could not get it to work for now

```
# groovy -v
Groovy Version: 2.3.7 JVM: 1.7.0_75 Vendor: Oracle Corporation OS: Linux
```

```
# java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

when i `cd sqsd/src` and `groovy sqsd.groovy` nothing happens, the cli just hang

I think this is related to the following line in sqsd.groovy:

`@Grab(group='com.amazonaws', module='aws-java-sdk', version='1.9.6')`

As i don't know much about java, any help would be appreciated

Thanks
Tom

**Comment by mortizbey** [comment]
Hey Tom,

Yes you are right, the Cli hangs because of that line but its just because it is downloading those dependencies. Those dependencies are relatively big (i think they are around 100MB) and unfortunately the Maven repositories in which these dependencies are stored are relatively slow. So, start the project and leave it running, after it downloads everything it should continue running. After it downloads it once, it will not need to download it anymore.

Let me know if it works.

Thanks,
Manuel

**Comment by tkleinhakisa** [comment]
Thank you Manuel, it worked fine !
